#ifndef __CameraSelectorDerived__
#define __CameraSelectorDerived__

/**
@file
Subclass of CameraSelector, which is generated by wxFormBuilder.
*/

#include "Frames/CameraSelector.h"
#include "../Camera/CameraSourceManager.h"
#include "../Camera/CameraSource.h"

#include "wx/filedlg.h"

/** Implementing CameraSelector */
class CameraSelectorDerived : public CameraSelector
{
private:
	CameraSourceManager *cCameraSourceManager;
protected:
	// Handlers for CameraSelector events.
	void OnCameraSelectorInit( wxInitDialogEvent& event );
	void OnFlip( wxCommandEvent& event );
	void OnSwap( wxCommandEvent& event );
	void OnMore( wxCommandEvent& event );
	void OnOK( wxCommandEvent& event );
	void OnCancel( wxCommandEvent& event );
	
public:
	/** Constructor */
	CameraSelectorDerived( CameraSourceManager* lCameraSourceManager, wxWindow* parent );
};

#endif // __CameraSelectorDerived__
