#ifndef __MainFrameDerived__
#define __MainFrameDerived__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "Frames/MainFrame.h"
#include "CameraSelectorDerived.h"

#include "wx/filedlg.h"

/** Implementing MainFrame */
class MainFrameDerived : public MainFrame
{
protected:
	// Handlers for MainFrame events.
	void OnVideoSelector1Change( wxCommandEvent& event );
	void OnVideoSelector2Change( wxCommandEvent& event );
	void OnVideoSelector3Change( wxCommandEvent& event );
	void OnVideoSelector4Change( wxCommandEvent& event );
	void LoadOptionsClicked( wxCommandEvent& event );
	void SaveOptionsClicked( wxCommandEvent& event );
	void ExitClicked( wxCommandEvent& event );
	void SelectCameraSourceClicked( wxCommandEvent& event );
	void StartCameraCaptureClicked( wxCommandEvent& event );
	void StopCameraCaptureClicked( wxCommandEvent& event );
	void StartVideoProcessingClicked( wxCommandEvent& event );
	void StopVideoProcessingClicked( wxCommandEvent& event );
	void StartVideoRecordingClicked( wxCommandEvent& event );
	void StopVideoRecordingClicked( wxCommandEvent& event );
	void OpenDebugLogClicked( wxCommandEvent& event );
	void HelpClicked( wxCommandEvent& event );
	void AboutClicked( wxCommandEvent& event );
	
public:
	/** Constructor */
	MainFrameDerived( wxWindow* parent );
};

#endif // __MainFrameDerived__
