#ifndef __Options1Derived__
#define __Options1Derived__

/**
@file
Subclass of Options1, which is generated by wxFormBuilder.
*/

#include "Frames/options1.h"
#include "../VideoProcessor.h"

struct ContoursOptions
{
	int Treshold;
};

// Results describing one found object (contour)
typedef struct S_MEAS_RESULTS_REC {
  int ObjNo;
  int MeritevNo;
  CvPoint2D32f Center;
  CvPoint2D32f Min;
  CvPoint2D32f Max;
  CvPoint2D32f Avg;
  CvPoint2D32f Stdd;
  int AllMeritev;
  float Area;
}T_MEAS_RESULTS_REC;

class ContoursProcessor: public VideoProcessor
{
private:
	//Gui and working version of our options
	ContoursOptions GuiVersion;
	ContoursOptions WorkingVersion;

	//Processing speciffic variables
	// Mem storage for contours
	CvMemStorage* storage;
	// Mem storage for results
	CvMemStorage* ResultsStorage;
	//Processed image(treshold)
	IplImage *pimg;
	//Source image
	IplImage *img;
	//Temporary image
	IplImage *Tmp_img;
	//Contours image
	IplImage *cnt_img;

	//Result from analyze of one image
	CvSeq* ImageResult;
	//Statistic results
	CvSeq* ImageStatResult;
	CvSeq* contours;
	//Results
	CvSeq *Results;

	//Count of measured images after reset
	int MeasurementImageCount;
	// Calculated contoure moments
	CvMoments Moments;  

#define MAX_CONTOURS 20

	//Processing speciffic functions
	bool InitProcessing();
	void CloseProcessing(void);
	bool FindContours();
	bool CalcResult(CvSeq *Results);

public:
	//Processes video frame and returns processed one
	IplImage* ProcessVideoFrame( IplImage *InputFrame );
	//Transfers new options to video processor(copy from vide
	bool TransferOptions();
	//Used by gui to set new treshold
	void SetTreshold( int Value );
	//Gets current contour objects
	CvSeq *GetContourObjects();
	//Gets statistic about contours
	CvSeq *GetStatistics();
	//Gets current results
	CvSeq *GetResults();
	//Gets the count of measured images
	int GetMeasurementImageCount();

	void ResetStatistics();

	ContoursProcessor( char* lname );
	~ContoursProcessor(){}
};

/** Implementing Options1 */
class Options1Derived : public Options1
{
private:
	ContoursProcessor *cContoursProcessor;

protected:
	// Handlers for Options1 events.
	void OnTreshold( wxScrollEvent& event );
	void OnResetStatistics( wxCommandEvent& event );
	
public:
	/** Constructor */
	Options1Derived( wxWindow* parent );
	Options1Derived( wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 240,230 ), long style = wxTAB_TRAVERSAL  );
};

#endif // __Options1Derived__
