#ifndef __Output1Derived__
#define __Output1Derived__

/**
@file
Subclass of Output1, which is generated by wxFormBuilder.
*/

#include "Frames/output1.h"
#include "../Output.h"
#include "Options1Derived.h"

#define MAX_STATISTIC_ELEMENTS 20

//For output statistic carculations
class OutputStatistics: public Output
{
private:
	//Grid to display data
	int sx;
	int sy;
	wxGrid * Grid;
	ContoursProcessor *cContoursProcessor;

public:
	bool DisplayOutputData();

	OutputStatistics( wxGrid *lGrid, ContoursProcessor *lContoursProcessor );
	void SpeedTest();
	~OutputStatistics(){}
};

/** Implementing Output1 */
class Output1Derived : public Output1
{
private:
	OutputStatistics *cOutputStatistics;

public:
	/** Constructor */
	Output1Derived( wxWindow* parent );
	Output1Derived( wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 240,230 ), long style = wxTAB_TRAVERSAL );
};

#endif // __Output1Derived__
