#ifndef __Output2Derived__
#define __Output2Derived__

/**
@file
Subclass of Output2, which is generated by wxFormBuilder.
*/

#include "Frames/output2.h"
#include "../Output.h"
#include "Options1Derived.h"

//For output statistic carculations
class OutputContourObjects: public Output
{
private:
	//Grid to display data
	wxGrid * Grid;
	ContoursProcessor *cContoursProcessor;

public:
	bool DisplayOutputData();

	OutputContourObjects( wxGrid *lGrid, ContoursProcessor *lContoursProcessor );
	~OutputContourObjects(){}
};


/** Implementing Output2 */
class Output2Derived : public Output2
{
private:
	OutputContourObjects *cOutputContourObjects;

public:
	/** Constructor */
	Output2Derived( wxWindow* parent );
	Output2Derived( wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 240,230 ), long style = wxTAB_TRAVERSAL );
};

#endif // __Output2Derived__
